### PR TITLE
Change some LE_KILL_CLIENT() to LE_CRIT()

### PR DESCRIPTION
**Pull request by jtchitty**
In an effort to make the system less brittle in the face of bugs
in clients of the Data Hub, several calls to LE_KILL_CLIENT() are
changed to LE_CRIT().

### CODE REVIEW

**Review by dpfrey — APPROVED** [review]
I know breaking interfaces is frowned upon, but I think that a better solution than LE_KILL_CLIENT or LE_CRITICAL is returning an error code to the caller.

**Comment by dpfrey** [comment]
Also, I'm not sure how much this change differs from Nicolas Joyeux's change in the other repository, but this change should at least partially be attributed to him.  A git commit can only have one author, but you can add a "Co-authored-by: name <name@example.com>" footer to the commit message.

**Comment by jtchitty** [comment]
> Also, I'm not sure how much this change differs from Nicolas Joyeux's change in the other repository, but this change should at least partially be attributed to him. A git commit can only have one author, but you can add a "Co-authored-by: name [name@example.com](mailto:name@example.com)" footer to the commit message.

Good point.  Will do.

**Comment by jtchitty** [comment]
> Also, I'm not sure how much this change differs from Nicolas Joyeux's change in the other repository, but this change should at least partially be attributed to him. A git commit can only have one author, but you can add a "Co-authored-by: name [name@example.com](mailto:name@example.com)" footer to the commit message.

**Comment by jtchitty** [comment]
> I know breaking interfaces is frowned upon, but I think that a better solution than LE_KILL_CLIENT or LE_CRITICAL is returning an error code to the caller.

I agree in any case that the client code can gracefully recovery by handling different errors in different ways.  But, if there's nothing the client can do to recover, then returning codes that they have to check just adds more complexity without any added value.  Furthermore, I strongly believe that errors should be reported close to where they are detected, so that valuable troubleshooting context can be reported before it is lost by unwinding the stack or performing other cleanup operations.

**Comment by jtchitty** [comment]
Can't just fix a commit message without changing the commit.  Deleting this branch.

**Pull request closed without merging**
